/*
!!!!!!!!!!!!!!
THIS FILE IS GENERATED BY "yarn icons" COMMAND. DO NOT CHANGE!
*/

import { ReactComponent as IconArrow } from 'src/assets/icons/icon-arrow.svg';
export const ICONS = {
"icon-arrow": IconArrow, 
};